// Generated by Wrangler by running `wrangler types`

interface Env {
	DISCORD_EVENTS: KVNamespace;
	FALLBACK_ORIGIN: string;
	PRIMARY_ORIGINS: { url: string, weight: number }[];
	MASTER_TOKEN: string;
}
