#:schema node_modules/wrangler/config-schema.json
name = "plural-api"
main = "src/index.ts"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[vars]
FALLBACK_ORIGIN = "https://api-0.plural.gg"
PRIMARY_ORIGINS = [
    { "url" = "https://api-1.plural.gg", "weight" = 1 },
    { "url" = "https://api-2.plural.gg", "weight" = 1 }
]

[[kv_namespaces]]
binding = "DISCORD_EVENTS"
id = "bb4c68a715df41539c6483654cce9c4b"